去掉运行时安装,根据我们的情况,直接预安装固定版本

diff --git a/runtime/functions b/runtime/functions
--- a/runtime/functions
+++ b/runtime/functions
@@ -193,13 +193,13 @@ initialize_database() {
           mv ${PG_HOME}/${PG_OLD_VERSION} ${PG_HOME}/${PG_OLD_VERSION}.migrating
 
           echo "‣ Installing PostgreSQL ${PG_OLD_VERSION}..."
-          if ! ( apt-get update &&  DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-${PG_OLD_VERSION} postgresql-client-${PG_OLD_VERSION} ) >/dev/null; then
-            echo "ERROR! Failed to install PostgreSQL ${PG_OLD_VERSION}. Exiting..."
-            # first move the old data back
-            rm -rf ${PG_HOME}/${PG_OLD_VERSION}
-            mv ${PG_HOME}/${PG_OLD_VERSION}.migrating ${PG_HOME}/${PG_OLD_VERSION}
-            exit 1
-          fi
+          #if ! ( apt-get update &&  DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-${PG_OLD_VERSION} postgresql-client-${PG_OLD_VERSION} ) >/dev/null; then
+          #  echo "ERROR! Failed to install PostgreSQL ${PG_OLD_VERSION}. Exiting..."
+          #  # first move the old data back
+          #  rm -rf ${PG_HOME}/${PG_OLD_VERSION}
+          #  mv ${PG_HOME}/${PG_OLD_VERSION}.migrating ${PG_HOME}/${PG_OLD_VERSION}
+          #  exit 1
+          #fi
           rm -rf /var/lib/apt/lists/*
 
           # we're ready to migrate, move back the old data and remove the trap
